version: '3'

services:
  backend:
    build: .
    command: python manage.py runserver 0.0.0.0:8002
    volumes:
      - .:/app
    ports:
      - "8002:8002"
    environment:
      - DJANGO_SETTINGS_MODULE=authentication.settings
    depends_on:
      - db
   

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: micro-authentication
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: albert



